# Copyright (c) 2023, MASSACHUSETTS INSTITUTE OF TECHNOLOGY
# Subject to FAR 52.227-11 – Patent Rights – Ownership by the Contractor (May 2014).
# SPDX-License-Identifier: MIT

# Example agent-environment configuration YAML for evaluation

user_id: "Evaluation Test"  # your individual team or user name goes here
user_key:  "f2dcf0d1-f977-4e8b-9103-d03be0bffeec" # your indivdiualized id goes here (distributed to you by organizers)
scenario_environment: PE1_E1_I3_V1
agent_module_path: "../src/kspdg/agent_api/example_agent.py"  # this must be relative to working directory when script is called
agent_cls: NaivePursuitAgent
agent_name: "Naive-Ned" # identifier name for logging purposes. 
                        # The same agent class with different inputs can lead to different behaviors,
                        # so you should give each instantiation their own name
agent_kwargs:
  arg1: value1
  arg2: value2
  arg3: value3
